stages:
  profile_generation:
    cmd: python dvc_pressure_map_gen.py
    deps:
    - dvc_pressure_map_gen.py
    params:
    - gengaus
    - random_seed
    - dataset.n_samples
    - env.sen_geometry.x_len
    - env.sen_geometry.y_len
    - env.pressure_profile

    outs:
    - data/pressure/pic
    #   - data/gaus_param.npy
  

  simulation:
    cmd: python dvc_sim_runner.py

    params:
    - random_seed
    - env.sen_geometry
    - env.phys
    - sim
    deps:
      - dvc_sim_runner.py
      - data/pressure/pic  
    outs:
    - data/sensor_signal

  learning:
    cmd: python dvc_model_learning.py

    params:
    - train

    deps:
      - data/sensor_signal
      - dvc_model_learning.py
      - torch_sensor_lib/nets.py
    outs:
    - data/model

    plots:
    - reports/learning_curve.csv:
        cache: false
        x_label: epochs
        y_label: loss
    metrics:
    - reports/summary.json:
        cache: false

  evaluation:
    cmd: python dvc_evaluate_model.py

    deps:
    - data/model
    - dvc_evaluate_model.py
    outs:
    - reports/report.md:
        cache: false
    - reports/l_curve.png:
        cache: false
    - reports/predict_examples.jpg:
        cache: false
    - logsdir

  make_plot:
    cmd: dvc plots diff 9a8d6 --x-label "epochs" --y-label "loss"

    deps:
    - reports/learning_curve.csv
    outs:
    - dvc_plots/index.html:
        cache: false

