stages:
  profile_generation:
    cmd: python3 dvc_pressure_map_gen.py
    deps:
      - dvc_pressure_map_gen.py
    params:
      - gengaus
      - random_seed
      - dataset.n_samples
      - dataset.pic_path
      - env.sen_geometry.x_len
      - env.sen_geometry.y_len
      - env.pressure_profile
      
    outs:
      - data/pressure/pic
    #   - data/gaus_param.npy
  
  batch_splitting:
    cmd: python3 dvc_sim_batch_split.py
    deps:
      - data/pressure/pic
      - dvc_sim_batch_split.py
    params:
      - sim.batch_size
      - sim.pic_path
      - dataset.pic_path
    outs:
      - data/pressure/batched_pic  

  simulate:
    cmd: python dvc_sim_runner.py
    
    params:
      - dataset.signal_path
      - dataset.pic_path
      - random_seed
      - env.sen_geometry
      - env.phys
      - sim
    deps:
      - dvc_sim_runner.py
      - data/pressure/batched_pic  
    outs:
      - data/sensor_signal

  learning:
    cmd: python3 dvc_model_learning.py

    params:
      - train

    deps:
      - data/sensor_signal
      - data/pressure/batched_pic  
      - dvc_model_learning.py
    outs:
      - data/model
      
    plots:
      - reports/learning_curve.csv:
          cache: false

    metrics:
      - reports/summary.json:
          cache: false

  evaluate:
    cmd: python3 dvc_evaluate_model.py

    deps:
    - data/model

    outs:
    - reports/report.md:
        cache: false
    - reports/l_curve.png:
        cache: false
    - reports/predict_examples.png:
        cache: false

  make_plot:
    cmd: dvc plots show reports/learning_curve.csv --x-label "epochs" --y-label "loss"

    outs:
    - dvc_plots/index.html:
        cache: false

