stages:
  prepare_dataset:
    cmd: python video_pipeline/prepare_dataset.py
  
  video_sim:
    cmd: python video_pipeline/video_sim_runner.py

  video_learning:
      cmd: python video_pipeline/learning.py
      params:
        - video_train

      metrics:
        - reports/v_summary.json:
            cache: false
      plots:
        - reports/video_lc.csv:
            cache: false
            y: test_loss
            x_label: epoch
      outs:
      - data/v_model
