stages:
  profile_generation:
    cmd: python dvc_pressure_map_gen.py
    deps:
      - dvc_pressure_map_gen.py
    params:
      - gengaus
      - random_seed
      - dataset.n_samples
      - env.sen_geometry.x_len
      - env.sen_geometry.y_len
      - env.pressure_profile
      
    outs:
      - data/pressure/pic
    #   - data/gaus_param.npy
  
  batch_splitting:
    cmd: python dvc_sim_batch_split.py
    deps:
      - data/pressure/pic
      - dvc_sim_batch_split.py
    params:
      - sim.batch_size
    outs:
      - data/pressure/batched_pic  

  simulation:
    cmd: python dvc_sim_runner.py
    
    params:
      - random_seed
      - env.sen_geometry
      - env.phys
      - sim
    deps:
      - dvc_sim_runner.py
      - data/pressure/batched_pic  
    outs:
      - data/sensor_signal

  learning:
    cmd: python dvc_model_learning.py

    params:
      - train

    deps:
      - data/sensor_signal
      - data/pressure/batched_pic  
      - dvc_model_learning.py
      - torch_sensor_lib/nets.py
    outs:
      - data/model
      
    plots:
      - reports/learning_curve.csv:
          cache: false

    metrics:
      - reports/summary.json:
          cache: false

  evaluation:
    cmd: python dvc_evaluate_model.py

    deps:
    - data/model
    - dvc_evaluate_model.py
    outs:
    - reports/report.md:
        cache: false
    - reports/l_curve.png:
        cache: false
    - reports/predict_examples.png:
        cache: false
    - logsdir

  make_plot:
    cmd: dvc plots diff 973a7c --x-label "epochs" --y-label "loss"

    deps:
    - reports/learning_curve.csv
    outs:
    - dvc_plots/index.html:
        cache: false

