vars:
  - logger.yaml 
stages:
  
  video_sim:
    cmd: python video_pipeline/video_sim_runner.py
    params:
        - env.sen_geometry.n_angles
        - env.phys.kof
        - env.phys.gaus_kernel_size
    deps:
        - video_pipeline/video_sim_runner.py
        - data/video/pressure
    outs:
        - data/video/signal

  video_learning:
      cmd: python video_pipeline/learning.py
      params:
        - video_train

      deps:
        - data/video/train_signal
        - data/video/test_signal

      metrics:
        - reports/v_summary.json:
            cache: false
      plots:
        - reports/full_test_loss.csv:
            cache: false
            x_label: epoch
        - reports/full_train_loss.csv:
            cache: false
            x_label: epoch
      outs:
      - data/v_model

  visual:
    cmd: python video_pipeline/prediction_visualization.py
    params:
      - visual
    deps:
      - data/v_model
    outs:
      - data/video/predict_vis

  push_logs:
    cmd: python csv_logger.py
    deps:
      - ${log_path}
