random_seed: 4732

gengaus:
  batch_size: 1000
  save_batch_size: None   # should be divisible by batch_size

env:
  pressure_profile:
    n_gauses: 7
    size_kof: 5
    g_param_path: data/gaus_param.npy

  sen_geometry:
    distance: 0.5     # between fibers in mm
    x_len: 64     # in pixels
    y_len: 64     # in pixels    
    n_angles: 4
    n_spl: 1     # number of pictures to show in testing mode  
  phys:
    fiber_sensibility:
      value: 0.6       # width of fiber in mm
      accuracy: 5       # it is (size of kernel)/value 
    kof: 1     # between apply force and loss in grams 
    relative_noise: 0.00     # in fiber transmission detection
    noise: 0.00     #  in fiber transmission detection
dataset:
  n_samples: 100_000

sim:
  random_rot: 1
  batch_size: 500  # if None - gengaus.batchsize/n_angles/2
  test_size: 1  # in batches
  # max_possible_size: 20000
  test_mod: false   # verbose mod for testing sim

train:
  batch_size: 200
  learning_rate: 0.0001
  n_epochs: 75
  model_name: ParamInterpCNN
  test_size: None   # if None, 1/20 fraction of dataset 
commit_to_compare: b2599b
