dataset:
  mult_coeff: 80
  test_frac: 0.1
  test_items:
env:
  phys:
    fiber_sensibility:
      value: 0.5
    gaus_kernel_size: 3
    kof: 1
    noise: 0.0
    relative_noise: 0.0
  sen_geometry:
    distance: 0.5
    n_angles: 4
    n_spl: 1
    x_len: 64
    y_len: 64
random_seed: 4732
seed: 716409876
sim:
  batch_size: 100
  gaussian_blur: 4
  random_rot: 1
  test_mod: false
test_batch_size: 1000
video_train:
  batch_size: 1000
  epochs: 140
  frames_interval: 1
  frames_number: 1
  layers:
  - 500
  - 500
  - 500
  - 500
  - 500
  learning_rate: 0.0001
  model_name: ParamSingle
visual:
  test:
    max_items: 128
    step: 32
  train:
    max_items: 32
    step: 32
