random_seed: 4732

env:
  sen_geometry:
    distance: 0.35     # between fibers in mm
    x_len: 64     # in pixels
    y_len: 64     # in pixels    
    n_angles: 4
  phys:
    fiber_sensibility:
    kof: 15     # between apply force and loss in grams 
    sigma: 0.8          # gaussian blur sigma in mm-s
    relative_noise: 0.00     # in fiber transmission detection
    noise: 0.00     #  in fiber transmission detection
    elasticity: 1   # coefficient between pressure and deformation of silicon 
  bimodal:
    period: 2.3     # period of two modes interference
    intermode_matrix:    # defines speed of decay and transferring of energy between modes
      [[1, 0.2],
      [0.1, 1]]
    main_loss_coeff: 1.5  # multiplies all coefficients in intermode matrix
    borning_modes: [1, 0.2] # amplitudes of primary and secondary modes borning from primary mode in beginning of sensor
    impact_modes: [1, 0.2]  # impact of primary and secondary modes to primary mode after sensor
dataset:
  mult_coeff: 80  # multiplies all pressures

sim:
  random_rot: 1
  batch_size: 100  # if None - gengaus.batchsize/n_angles/2
  test_mod: false   # verbose mod for testing sim


video_train:
  batch_size: 1000    # for learning
  learning_rate: 0.0001
  epochs: 50
  # list of (number epochs, chain_len) pairs
  model_name: ParamUnet
  layers: [16, 32, 64, 64, 64, 64, 32, 16]

  frames_number: 1
  frames_interval: 1
test_batch_size: 1000  # for evaluations without grads

visual:
  test/test:
    step: 32
    max_items: 128
    # begin: 0
  train/train_videos:
    step: 32
    max_items: 32
  # train/train_gaus:
  #   max_items: 128  
  #   step: 1
  #   end: 20
  #   duration: 1000
