random_seed: 4732

env:
    presure_profile:
        n_gauses: 10
        size_kof: 5
        g_param_path: 'data/gaus_param.npy'

    sen_geometry:
        distanse: 0.5 # between fibers in mm
        x_len: 64 # in pixels
        y_len: 64 # in pixels    
        n_angles: 4
        n_spl: 1 # show  
    
    phys:
        fiber_sensibility : 
            value: 0.6 # width of fiber in mm
            accuracy: 4 # it is (size of kernl)/value 
        kof: 1 # between aply forse and loss in gramms 
        reletive_nose: 0.01 # in fiber transmition detection
        nose: 0.01 #  in fiber transmition detection
    
dataset:
    pic_path: 'data/presure/pic'
    # video_path: 'data/presure/pic' for future
    n_sampels: 200

sim:
    pic_path: 'data/fiber_loss/pic'
    # video_path: 'data/fiber_loss/video' for future
    random_rot: 1
    batch_size: 128
    test_size: 'None'
    max_possible_size: 1000
    test_mod: True # verbose mod for testing sim

train:
    models_path: 'models'
    batch_size: 128
    lerning_rate: 0.0001
    n_epochs: 20

evaluate:
    reports_path: 'reports'     
    pred_path: 'predicts'