random_seed: 4732

env:
  sen_geometry:
    distance: 0.5     # between fibers in mm
    x_len: 64     # in pixels
    y_len: 64     # in pixels    
    n_angles: 4
    n_spl: 1     # number of pictures to show in testing mode  
  phys:
    fiber_sensibility:
      value: 0.5       # width of fiber in mm
      # accuracy: 5       # it is [size of kernel]/value 
    kof: 15     # between apply force and loss in grams 
    gaus_kernel_size: 13  # odd integer!!
    relative_noise: 0.00     # in fiber transmission detection
    noise: 0.00     #  in fiber transmission detection
dataset:
  mult_coeff: 80  # multiplies all pressures

sim:
  random_rot: 1
  batch_size: 100  # if None - gengaus.batchsize/n_angles/2
  test_mod: false   # verbose mod for testing sim


video_train:
  batch_size: 1000    # for learning
  learning_rate: 0.0001
  epochs: 36
  # list of (number epochs, chain_len) pairs
  model_name: ParamUnet
  layers: [4,8,16,32,64,64,32,16,8,4]

  frames_number: 1
  frames_interval: 1
test_batch_size: 1000  # for evaluations without grads

visual:
  test/test:
    step: 32
    max_items: 128
    # begin: 0
  train/train_videos:
    step: 32
    max_items: 32
  # train/gaus:  
  #   end: 20
  #   duration: 1000
