random_seed: 4732

env:
    pressure_profile:
        n_gauses: 10
        size_kof: 5
        g_param_path: 'data/gaus_param.npy'

    sen_geometry:
        distance: 0.5 # between fibers in mm
        x_len: 64 # in pixels
        y_len: 64 # in pixels    
        n_angles: 4
        n_spl: 1 # show  
    
    phys:
        fiber_sensibility : 
            value: 0.6 # width of fiber in mm
            accuracy: 4 # it is (size of kernel)/value 
        kof: 1 # between apply force and loss in grams 
        relative_noise: 0.01 # in fiber transmission detection
        noise: 0.01 #  in fiber transmission detection
    
dataset:
    pic_path: 'data/pressure/pic'
    # video_path: 'data/pressure/pic' for future
    n_samples: 150

sim:
    pic_path: 'data/fiber_loss/pic'
    # video_path: 'data/fiber_loss/video' for future
    random_rot: 1
    batch_size: 128
    test_size: 'None'
    max_possible_size: 20000
    test_mod: True # verbose mod for testing sim

train:
    models_path: 'models'
    batch_size: 128
    learning_rate: 0.0001
    n_epochs: 20

evaluate:
    reports_path: 'reports'     
    pred_path: 'predicts'