random_seed: 4732

gengaus:
    batch_size: 1000
    save_batch_size: None # should be divisible by batch_size

env:
  pressure_profile:
    n_gauses: 30
    size_kof: 5
    g_param_path: data/gaus_param.npy

  sen_geometry:
    distance: 0.5     # between fibers in mm
    x_len: 64     # in pixels
    y_len: 64     # in pixels    
    n_angles: 4
    n_spl: 1     # number of pictures to show in testing mode  
  phys:
    fiber_sensibility:
      value: 0.6       # width of fiber in mm
      accuracy: 4       # it is (size of kernel)/value 
    kof: 1     # between apply force and loss in grams 
    relative_noise: 0.01     # in fiber transmission detection
    noise: 0.01     #  in fiber transmission detection
    
dataset:
  pic_path: data/pressure/pic
  signal_path: data/sensor_signal
    # video_path: 'data/pressure/pic' for future
  n_samples: 100_000

sim:
  pic_path: data/pressure/batched_pic
    # video_path: 'data/fiber_loss/video' for future
  random_rot: 1
  batch_size: 100  # is None - gengaus.batchsize/n_angles/2
  test_size: None
  # max_possible_size: 20000
  test_mod: false   # verbose mod for testing sim

train:
  models_path: data/model
  # batch_size: 128       # in torch nets sim.batch_size is used
  learning_rate: 0.0001
  n_epochs: 50
  model_name: TorchSensorNN5S_norm_deep

evaluate:
  reports_path: reports
  pred_path: predicts
