random_seed: 4732

env:
  sen_geometry:
    distance: 0.5     # between fibers in mm
    x_len: 64     # in pixels
    y_len: 64     # in pixels    
    n_angles: 4
    n_spl: 1     # number of pictures to show in testing mode  
  phys:
    fiber_sensibility:
      value: 0.5       # width of fiber in mm
      # accuracy: 5       # it is [size of kernel]/value 
    kof: 1     # between apply force and loss in grams 
    gaus_kernel_size: 3  # odd integer!!
    relative_noise: 0.00     # in fiber transmission detection
    noise: 0.00     #  in fiber transmission detection
dataset:
  test_items:
  test_frac: 0.1
  mult_coeff: 80  # multiplies all pressures

sim:
  random_rot: 1
  batch_size: 100  # if None - gengaus.batchsize/n_angles/2
  test_mod: false   # verbose mod for testing sim


video_train:
  batch_size: 1000    # for learning
  learning_rate: 0.0001
  epochs: 12
  # list of (number epochs, chain_len) pairs
  model_name: Unet2
  # layers: [10, 10, 10, 10, 10, 10]        # single layers
  frames_number: 1
  frames_interval: 1
test_batch_size: 1000  # for evaluations without grads

visual:
  test:
    step: 16
    max_items: 128
    # begin: 0
  train:
    step: 32
    max_items: 64
